// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionsService.Data;

namespace SolutionsService.Migrations
{
    [DbContext(typeof(SolutionsServiceContext))]
    [Migration("20211111123556_modelUpdateRTR")]
    partial class modelUpdateRTR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SDGSolution", b =>
                {
                    b.Property<Guid>("SDGsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SolutionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SDGsId", "SolutionsId");

                    b.HasIndex("SolutionsId");

                    b.ToTable("SDGSolution");
                });

            modelBuilder.Entity("SolutionsService.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("SolutionsService.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SolutionsService.Models.SDG", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDGNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SDGs");
                });

            modelBuilder.Entity("SolutionsService.Models.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("WeatherExtreme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Solutions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Solution");
                });

            modelBuilder.Entity("SolutionsService.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("SolutionsService.Models.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HowToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HowToId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("SolutionsService.Models.HowTo", b =>
                {
                    b.HasBaseType("SolutionsService.Models.Solution");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("HowTo");
                });

            modelBuilder.Entity("SDGSolution", b =>
                {
                    b.HasOne("SolutionsService.Models.SDG", null)
                        .WithMany()
                        .HasForeignKey("SDGsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionsService.Models.Solution", null)
                        .WithMany()
                        .HasForeignKey("SolutionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolutionsService.Models.Like", b =>
                {
                    b.HasOne("SolutionsService.Models.Solution", "Solution")
                        .WithMany("Likes")
                        .HasForeignKey("SolutionId");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("SolutionsService.Models.Material", b =>
                {
                    b.HasOne("SolutionsService.Models.HowTo", "Solution")
                        .WithMany("Materials")
                        .HasForeignKey("SolutionId");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("SolutionsService.Models.Step", b =>
                {
                    b.HasOne("SolutionsService.Models.HowTo", "Solution")
                        .WithMany("Steps")
                        .HasForeignKey("SolutionId");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("SolutionsService.Models.Tool", b =>
                {
                    b.HasOne("SolutionsService.Models.HowTo", null)
                        .WithMany("Tools")
                        .HasForeignKey("HowToId");
                });

            modelBuilder.Entity("SolutionsService.Models.Solution", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("SolutionsService.Models.HowTo", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Steps");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
