version: '3.8'
services:

  solution-service: 
    build: 
      context: "."
      dockerfile: "Dockerfile.local"
    hostname: solution-service
    container_name: solution-service
    ports:
      - "5000:80"
    depends_on:
      - db-mssql      

  ocelot-gateway:
    build:
      context: "../../GGCGateWay/GGCGateWay"
      dockerfile: "Dockerfile"
    hostname: ocelot-gateway
    container_name: ocelot-gateway
    ports:
      - "5011:80"
    depends_on:
      - solution-service

  db-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    user: root
    container_name: db-mssql
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=informationDashboard1
    ports:
     - "1433:1433"
    volumes:
     - db-mssql:/var/opt/mssql/data
volumes:
  db-mssql: