version: '3.8'
services:

  solution-service: 
    build: 
      context: "."
      dockerfile: "Dockerfile"
    hostname: solution-service
    container_name: solution-service
    ports:
      - "5000:80"
    restart: always
    environment:
      "PUBLIC_PORT": "80"

  ocelot-gateway:
    build:
      context: "../../GGCGateWay/GGCGateWay"
      dockerfile: "Dockerfile"
    hostname: ocelot-gateway
    container_name: ocelot-gateway
    ports:
      - "5011:80"
    links:
      - solution-service
    depends_on:
      - solution-service

  db-solution:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db-solution"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "informationdashboard"
      MYSQL_ROOT_PASSWORD: "informationdashboard"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db-solution:/var/lib/mysql
volumes:
  db-solution: